-- CS Family Star — database schema, constraints and policies.
--
-- Run this once in the Supabase SQL editor (Dashboard → SQL Editor → New query).
-- It is idempotent: running it twice is safe.
--
-- The app works without it (the API routes degrade gracefully), but until you run it
-- there is no `price_per_person` column, no aggregate view, and no Row Level Security
-- — which means anyone holding the public anon key can write whatever they like
-- straight into your table, bypassing the validation in /api/reviews.

-- ─────────────────────────────────────────────────────────────────────────────
-- 1. Table
-- ─────────────────────────────────────────────────────────────────────────────

create table if not exists public.reviews (
  id               bigint generated by default as identity primary key,
  restaurant_id    text        not null,
  rating           smallint    not null,
  comment          text,
  user_name        text,
  image_url        text,
  price_per_person integer,
  recommended_dish text,
  created_at       timestamptz not null default now()
);

-- Added for the "average price" feature. Safe on an existing table.
alter table public.reviews add column if not exists price_per_person integer;

-- Added for the "what should I order" feature. Without this column the API's
-- fallback path silently dropped the dish a student typed: it was accepted by the
-- form, passed validation, and then thrown away on insert.
alter table public.reviews add column if not exists recommended_dish text;

-- ─────────────────────────────────────────────────────────────────────────────
-- 2. Constraints
--
-- NOT VALID means these apply to every new row but do not fail the migration on
-- rows you already have. Once you have cleaned up any old bad rows, run:
--     alter table public.reviews validate constraint reviews_rating_range;
-- ─────────────────────────────────────────────────────────────────────────────

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'reviews_rating_range') then
    alter table public.reviews
      add constraint reviews_rating_range check (rating between 1 and 5) not valid;
  end if;

  if not exists (select 1 from pg_constraint where conname = 'reviews_comment_length') then
    alter table public.reviews
      add constraint reviews_comment_length check (char_length(comment) <= 500) not valid;
  end if;

  if not exists (select 1 from pg_constraint where conname = 'reviews_user_name_length') then
    alter table public.reviews
      add constraint reviews_user_name_length check (char_length(user_name) <= 60) not valid;
  end if;

  if not exists (select 1 from pg_constraint where conname = 'reviews_price_range') then
    alter table public.reviews
      add constraint reviews_price_range
      check (price_per_person is null or price_per_person between 1 and 10000) not valid;
  end if;

  if not exists (select 1 from pg_constraint where conname = 'reviews_restaurant_id_length') then
    alter table public.reviews
      add constraint reviews_restaurant_id_length
      check (char_length(restaurant_id) between 1 and 100) not valid;
  end if;

  if not exists (select 1 from pg_constraint where conname = 'reviews_recommended_dish_length') then
    alter table public.reviews
      add constraint reviews_recommended_dish_length
      check (char_length(recommended_dish) <= 60) not valid;
  end if;
end $$;

-- ─────────────────────────────────────────────────────────────────────────────
-- 3. Indexes
-- ─────────────────────────────────────────────────────────────────────────────

-- Serves the per-venue reviews feed, which orders by created_at descending.
create index if not exists reviews_restaurant_created_idx
  on public.reviews (restaurant_id, created_at desc);

-- ─────────────────────────────────────────────────────────────────────────────
-- 4. Aggregate view
--
-- /api/restaurants reads this instead of pulling every review row into Node and
-- summing them there. Postgres does the aggregation; the API does one round trip.
-- ─────────────────────────────────────────────────────────────────────────────

create or replace view public.review_stats
with (security_invoker = on) as
select
  restaurant_id,
  sum(rating)::bigint                                     as rating_sum,
  count(*)::bigint                                        as rating_count,
  coalesce(sum(price_per_person), 0)::bigint              as price_sum,
  count(price_per_person)::bigint                         as price_count
from public.reviews
group by restaurant_id;

-- ─────────────────────────────────────────────────────────────────────────────
-- 5. Row Level Security
--
-- Pick ONE of the two write policies below.
-- ─────────────────────────────────────────────────────────────────────────────

alter table public.reviews enable row level security;

-- Everyone can read reviews. This is a public guide.
drop policy if exists "reviews are publicly readable" on public.reviews;
create policy "reviews are publicly readable"
  on public.reviews for select
  to anon, authenticated
  using (true);

-- OPTION A (default) — the browser may insert, but only well-formed rows.
-- Use this if you have NOT set SUPABASE_SERVICE_ROLE_KEY.
drop policy if exists "anyone may add a well-formed review" on public.reviews;
create policy "anyone may add a well-formed review"
  on public.reviews for insert
  to anon, authenticated
  with check (
    rating between 1 and 5
    and char_length(coalesce(comment, '')) <= 500
    and char_length(coalesce(user_name, '')) <= 60
    and (price_per_person is null or price_per_person between 1 and 10000)
    and char_length(coalesce(recommended_dish, '')) <= 60
    and (image_url is null or image_url like 'https://%/storage/v1/object/public/review-images/%')
  );

-- OPTION B (stricter) — only the server may write, so every insert must pass the
-- validation in /api/reviews. Set SUPABASE_SERVICE_ROLE_KEY in .env.local, then
-- comment out OPTION A above and uncomment this:
--
--   drop policy if exists "anyone may add a well-formed review" on public.reviews;
--
-- The service-role key bypasses RLS, so no insert policy is needed at all.

-- Nobody may edit or delete through the public API. Do it from the dashboard.
drop policy if exists "no public updates" on public.reviews;
drop policy if exists "no public deletes" on public.reviews;

-- ─────────────────────────────────────────────────────────────────────────────
-- 6. Storage bucket for review photos
-- ─────────────────────────────────────────────────────────────────────────────

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'review-images',
  'review-images',
  true,
  5242880,                                                       -- 5 MB
  array['image/jpeg', 'image/png', 'image/webp', 'image/gif']
)
on conflict (id) do update
  set public             = excluded.public,
      file_size_limit    = excluded.file_size_limit,
      allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "review images are publicly readable" on storage.objects;
create policy "review images are publicly readable"
  on storage.objects for select
  to anon, authenticated
  using (bucket_id = 'review-images');

drop policy if exists "anyone may upload a review image" on storage.objects;
create policy "anyone may upload a review image"
  on storage.objects for insert
  to anon, authenticated
  with check (bucket_id = 'review-images');
-- ─────────────────────────────────────────────────────────────────────────────
-- 7. Study-spot attributes
--
-- Crowd-sourced yes/no votes on whether a venue is somewhere you can actually
-- work: Wi-Fi, sockets, noise, seating. One vote per browser per venue per
-- attribute, enforced by a unique constraint rather than trusted from the client.
-- ─────────────────────────────────────────────────────────────────────────────

create table if not exists public.venue_attributes (
  id          bigint generated by default as identity primary key,
  venue_id    text        not null,
  attribute   text        not null,
  value       boolean     not null,
  -- A random id generated in the browser and kept in localStorage. Not an
  -- identity and not trusted for anything but de-duplication: someone who clears
  -- storage can vote again, which is an acceptable cost for having no accounts.
  voter_token text        not null,
  created_at  timestamptz not null default now()
);

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'venue_attributes_known') then
    alter table public.venue_attributes
      add constraint venue_attributes_known
      check (attribute in ('wifi', 'power', 'quiet', 'seating', 'aircon', 'long_stay')) not valid;
  end if;

  if not exists (select 1 from pg_constraint where conname = 'venue_attributes_ids_sane') then
    alter table public.venue_attributes
      add constraint venue_attributes_ids_sane
      check (
        char_length(venue_id) between 1 and 100
        and char_length(voter_token) between 8 and 64
      ) not valid;
  end if;
end $$;

-- One vote per voter per venue per attribute. A re-vote updates in place via
-- `on conflict`, so changing your mind is allowed but ballot-stuffing is not.
create unique index if not exists venue_attributes_one_vote_idx
  on public.venue_attributes (venue_id, attribute, voter_token);

create index if not exists venue_attributes_venue_idx
  on public.venue_attributes (venue_id);

-- Aggregate view, so the API does one round trip instead of summing in Node.
create or replace view public.venue_attribute_stats
with (security_invoker = on) as
select
  venue_id,
  attribute,
  count(*) filter (where value)::bigint as yes_count,
  count(*)::bigint                      as total_count
from public.venue_attributes
group by venue_id, attribute;

alter table public.venue_attributes enable row level security;

drop policy if exists "attribute votes are publicly readable" on public.venue_attributes;
create policy "attribute votes are publicly readable"
  on public.venue_attributes for select
  to anon, authenticated
  using (true);

-- Mirrors the CHECK constraints above so the rules hold even if a client talks to
-- PostgREST directly with the anon key, bypassing /api entirely.
drop policy if exists "anyone may vote on an attribute" on public.venue_attributes;
create policy "anyone may vote on an attribute"
  on public.venue_attributes for insert
  to anon, authenticated
  with check (
    attribute in ('wifi', 'power', 'quiet', 'seating', 'aircon', 'long_stay')
    and char_length(venue_id) between 1 and 100
    and char_length(voter_token) between 8 and 64
  );

-- Changing your own vote is allowed; the unique index scopes it to your token.
drop policy if exists "voters may change their own vote" on public.venue_attributes;
create policy "voters may change their own vote"
  on public.venue_attributes for update
  to anon, authenticated
  using (true)
  with check (
    attribute in ('wifi', 'power', 'quiet', 'seating', 'aircon', 'long_stay')
  );
