import type { RestaurantMenu } from './types';
import { BRAND_ALIASES, type CachedTalabatRestaurant } from './talabat';
import talabatCachedData from './talabatMenusData.json';

/**
 * Menu Catalog for FUE On-Campus Restaurants.
 *
 * You can provide or edit any restaurant's menu items here directly,
 * or use the in-app "Provide Menu" option on any restaurant card.
 */
export const DEFAULT_MENUS: Record<string, RestaurantMenu> = {
  'fue-cilantro': {
    restaurantId: 'fue-cilantro',
    restaurantName: 'Cilantro - FUE Campus',
    currency: 'EGP',
    lastUpdated: '2026-09-14',
    note: 'Located inside FUE Campus Food Court. Student ID discount applicable on select beverages.',
    categories: ['Hot Drinks', 'Iced & Cold Drinks', 'Sandwiches & Wraps', 'Bakery & Desserts'],
    items: [
      {
        id: 'cil-1',
        name: 'Iced Spanish Latte',
        nameAr: 'سبانيش لاتيه مثلج',
        description: 'Rich espresso with condensed milk and chilled fresh milk over ice',
        price: 95,
        category: 'Iced & Cold Drinks',
        isPopular: true,
        isStudentDeal: true,
      },
      {
        id: 'cil-2',
        name: 'Caramel Macchiato',
        nameAr: 'كاراميل ماكياتو',
        description: 'Freshly steamed milk with vanilla-flavored syrup marked with espresso and topped with caramel drizzle',
        price: 90,
        category: 'Hot Drinks',
        isPopular: true,
      },
      {
        id: 'cil-3',
        name: 'Smoked Turkey & Emmental Croissant',
        nameAr: 'كرواسون ديك رومي وجبنة إيمنتال',
        description: 'Fresh flaky butter croissant filled with smoked turkey slices and melted French cheese',
        price: 85,
        category: 'Sandwiches & Wraps',
        isPopular: true,
      },
      {
        id: 'cil-4',
        name: 'Halloumi & Pesto Panini',
        nameAr: 'بانيني حلوم بالبيستو',
        description: 'Grilled halloumi cheese with fresh basil pesto and sun-dried tomatoes on ciabatta',
        price: 110,
        category: 'Sandwiches & Wraps',
        isVegetarian: true,
      },
      {
        id: 'cil-5',
        name: 'Double Espresso',
        nameAr: 'دوبل إسبريسو',
        description: 'Intense double shot of premium Arabica espresso blend',
        price: 55,
        category: 'Hot Drinks',
      },
      {
        id: 'cil-6',
        name: 'Iced Matcha Green Tea Latte',
        nameAr: 'ماتشا لاتيه مثلج',
        description: 'Japanese ceremonial grade matcha lightly sweetened and shaken with milk',
        price: 115,
        category: 'Iced & Cold Drinks',
      },
      {
        id: 'cil-7',
        name: 'Nutella Brownie Slice',
        nameAr: 'براوني بالنوتيلا',
        description: 'Warm fudge brownie loaded with dark chocolate chips and warm hazelnut cream',
        price: 70,
        category: 'Bakery & Desserts',
      },
    ],
  },

  'fue-pasta2go': {
    restaurantId: 'fue-pasta2go',
    restaurantName: 'Pasta 2Go',
    currency: 'EGP',
    lastUpdated: '2026-09-14',
    note: 'FUE Student Food Court. Custom pasta bowls made to order in 5-8 minutes.',
    categories: ['Signature Pastas', 'Build Your Own Pasta', 'Appetizers & Sides', 'Beverages'],
    items: [
      {
        id: 'p2g-1',
        name: 'Crispy Chicken Alfredo Penne',
        nameAr: 'بيني ألفريدو دجاج مقرمش',
        description: 'Penne tossed in creamy rich parmesan garlic sauce, topped with crunchy fried chicken tenders and fresh parsley',
        price: 135,
        category: 'Signature Pastas',
        isPopular: true,
        isStudentDeal: true,
      },
      {
        id: 'p2g-2',
        name: 'Pink Sauce Funghi Chicken',
        nameAr: 'باستا بينك صوص مشروم ودجاج',
        description: 'Fussili in our secret blend of marinara and white cream sauce with sautéed mushrooms and chicken strips',
        price: 140,
        category: 'Signature Pastas',
        isPopular: true,
      },
      {
        id: 'p2g-3',
        name: 'Spicy Arrabiata Pasta',
        nameAr: 'باستا أرابياتا حارة',
        description: 'Penne in spicy tomato basil sauce, black olives, garlic, and red chili flakes',
        price: 85,
        category: 'Signature Pastas',
        isVegetarian: true,
        isSpicy: true,
      },
      {
        id: 'p2g-4',
        name: 'Four Cheese Mac & Cheese',
        nameAr: 'ماك أند تشيز 4 أجبان',
        description: 'Elbow macaroni baked with cheddar, mozzarella, gouda, and parmesan cheese crust',
        price: 120,
        category: 'Signature Pastas',
        isPopular: true,
      },
      {
        id: 'p2g-5',
        name: 'Mozzarella Cheese Sticks (4 pcs)',
        nameAr: 'أصابع جبنة موتزاريلا',
        description: 'Crispy golden breaded mozzarella sticks served with warm marinara dipping sauce',
        price: 65,
        category: 'Appetizers & Sides',
      },
      {
        id: 'p2g-6',
        name: 'Cheesy Garlic Bread',
        nameAr: 'خبز بالثوم والجبنة',
        description: 'Toasted baguette with garlic herb butter and melted mozzarella',
        price: 50,
        category: 'Appetizers & Sides',
        isVegetarian: true,
      },
      {
        id: 'p2g-7',
        name: 'Soft Drink (Can)',
        nameAr: 'مشروب غازي',
        description: 'Pepsi, Diet Pepsi, 7Up, or Mirinda',
        price: 25,
        category: 'Beverages',
      },
    ],
  },

  'fue-seven-days': {
    restaurantId: 'fue-seven-days',
    restaurantName: 'Seven Days Cafe',
    currency: 'EGP',
    lastUpdated: '2026-09-14',
    note: 'FUE Campus Courtyard. Outdoor seating and charging spots available.',
    categories: ['Coffee & Espresso', 'Fresh Juices & Smoothies', 'Snacks & Toasties', 'Desserts'],
    items: [
      {
        id: 'sd-1',
        name: 'Iced Caramel Macchiato',
        nameAr: 'ماكياتو كراميل مثلج',
        description: 'Fresh espresso shot layered over milk with vanilla syrup and caramel drizzle',
        price: 80,
        category: 'Coffee & Espresso',
        isPopular: true,
      },
      {
        id: 'sd-2',
        name: 'FUE Student Breakfast Toastie',
        nameAr: 'توست فطور الطلاب',
        description: 'Toasted brioche with scrambled eggs, cheddar cheese, and beef bacon or turkey',
        price: 75,
        category: 'Snacks & Toasties',
        isStudentDeal: true,
        isPopular: true,
      },
      {
        id: 'sd-3',
        name: 'Fresh Mango Mint Smoothie',
        nameAr: 'سموذي مانجو بالنعناع',
        description: 'Blended fresh natural mango chunks with mint leaves and crushed ice',
        price: 70,
        category: 'Fresh Juices & Smoothies',
        isPopular: true,
      },
      {
        id: 'sd-4',
        name: 'Club Sandwich Supreme',
        nameAr: 'كلوب ساندوتش سوبريم',
        description: 'Triple-decker toasted bread with grilled chicken, eggs, cheese, lettuce, and mayo with chips',
        price: 115,
        category: 'Snacks & Toasties',
      },
      {
        id: 'sd-5',
        name: 'Turkish Coffee (Double)',
        nameAr: 'قهوة تركي دوبل',
        description: 'Traditional slow-brewed Turkish coffee with cardamom',
        price: 40,
        category: 'Coffee & Espresso',
      },
      {
        id: 'sd-6',
        name: 'Lotus Biscoff Cheesecake',
        nameAr: 'تشيز كيك لوتس',
        description: 'Creamy New York style cheesecake topped with melted Lotus spread and crushed biscuit',
        price: 85,
        category: 'Desserts',
      },
    ],
  },

  'fue-tbs-campus': {
    restaurantId: 'fue-tbs-campus',
    restaurantName: 'TBS (The Bakery Shop) - FUE Campus',
    currency: 'EGP',
    lastUpdated: '2026-09-14',
    note: 'FUE Engineering Building Plaza. Fresh bakery batches baked every morning.',
    categories: ['Fresh Croissants & Puffs', 'Gourmet Sandwiches', 'Coffee & Tea', 'Cookies & Treats'],
    items: [
      {
        id: 'tbs-1',
        name: 'Almond Butter Croissant',
        nameAr: 'كرواسون لوز بالزبدة',
        description: 'Double-baked croissant filled with almond frangipane cream and topped with sliced toasted almonds',
        price: 75,
        category: 'Fresh Croissants & Puffs',
        isPopular: true,
      },
      {
        id: 'tbs-2',
        name: 'Grilled Halloumi & Tapenade Focaccia',
        nameAr: 'فوكاشيا حلوم مشوي وزيتون',
        description: 'Fresh olive oil focaccia bread with grilled halloumi cheese, black olive tapenade, and rocca',
        price: 95,
        category: 'Gourmet Sandwiches',
        isVegetarian: true,
        isPopular: true,
      },
      {
        id: 'tbs-3',
        name: 'Smoked Salmon & Cream Cheese Bagel',
        nameAr: 'بيجل سلمون مدخن وكريمة',
        description: 'Toasted sesame bagel with Norwegian smoked salmon, capers, dill, and cream cheese',
        price: 160,
        category: 'Gourmet Sandwiches',
      },
      {
        id: 'tbs-4',
        name: 'Pain au Chocolat',
        nameAr: 'بان أو شوكولا',
        description: 'Flaky Viennoiserie pastry with two batons of Belgian dark chocolate',
        price: 60,
        category: 'Fresh Croissants & Puffs',
      },
      {
        id: 'tbs-5',
        name: 'FUE Morning Combo: Croissant + Cappuccino',
        nameAr: 'عرض الصباح: كرواسون + كابتشينو',
        description: 'Plain or cheese croissant paired with a hot 12oz cappuccino',
        price: 90,
        category: 'Coffee & Tea',
        isStudentDeal: true,
        isPopular: true,
      },
    ],
  },

  'fue-cinnabon-campus': {
    restaurantId: 'fue-cinnabon-campus',
    restaurantName: "Cinnabon & Seattle's Best - FUE Campus",
    currency: 'EGP',
    lastUpdated: '2026-09-14',
    note: 'FUE Student Center Kiosk. Warm rolls straight out of the oven.',
    categories: ['Cinnabon Rolls', 'Minibon & BonBites', 'Seattle’s Best Coffee', 'Chillattas'],
    items: [
      {
        id: 'cin-1',
        name: 'Caramel Pecanbon Roll',
        nameAr: 'كراميل بيكانبون رول',
        description: 'World-famous warm cinnamon roll topped with rich caramel glaze and crunchy toasted pecans',
        price: 110,
        category: 'Cinnabon Rolls',
        isPopular: true,
      },
      {
        id: 'cin-2',
        name: 'Classic Cinnabon Roll',
        nameAr: 'سينامون رول كلاسيك',
        description: 'Freshly baked Makara cinnamon dough smothered in legendary cream cheese frosting',
        price: 95,
        category: 'Cinnabon Rolls',
        isPopular: true,
      },
      {
        id: 'cin-3',
        name: 'Classic Minibon (Single)',
        nameAr: 'ميني بون كلاسيك',
        description: 'Smaller portion of our famous classic roll with warm cream cheese frosting',
        price: 65,
        category: 'Minibon & BonBites',
        isStudentDeal: true,
      },
      {
        id: 'cin-4',
        name: 'BonBites (4 Pieces Pack)',
        nameAr: 'بون بايتس 4 قطع',
        description: 'Bite-sized cinnamon roll treats, perfect for sharing with friends',
        price: 75,
        category: 'Minibon & BonBites',
      },
      {
        id: 'cin-5',
        name: 'Iced Mocha Chillatta',
        nameAr: 'موكا تشيلاتا مثلج',
        description: 'Blended frozen espresso, chocolate fudge, and milk topped with whipped cream',
        price: 95,
        category: 'Chillattas',
      },
      {
        id: 'cin-6',
        name: 'Seattle’s Best Brewed Coffee',
        nameAr: 'قهوة أمريكان سياتلز بيست',
        description: 'Signature smooth medium-roast drip coffee',
        price: 55,
        category: 'Seattle’s Best Coffee',
      },
    ],
  },

  'fue-buffalo-campus': {
    restaurantId: 'fue-buffalo-campus',
    restaurantName: 'Buffalo Burger Express - FUE Food Court',
    currency: 'EGP',
    lastUpdated: '2026-09-14',
    note: 'FUE Student Food Court. 100% pure beef patties and real cheddar cheese.',
    categories: ['Burgers', 'Chicken Sandwiches', 'Student Combos', 'Loaded Fries & Sides'],
    items: [
      {
        id: 'buf-1',
        name: 'Shiitake Mushroom Beef Burger (150g)',
        nameAr: 'برجر شيتاكي مشروم',
        description: 'Flame-grilled pure beef patty, sautéed fresh mushrooms, creamy mayonnaise, and melted Swiss cheese',
        price: 155,
        category: 'Burgers',
        isPopular: true,
      },
      {
        id: 'buf-2',
        name: 'The Secret Weapon Burger',
        nameAr: 'سيكريت ويبون برجر',
        description: 'Beef patty topped with caramelized onions, sharp cheddar cheese, pickles, and secret Buffalo sauce',
        price: 145,
        category: 'Burgers',
        isPopular: true,
      },
      {
        id: 'buf-3',
        name: 'Crispy Chicky Chicky Sandwich',
        nameAr: 'ساندوتش تشيكي تشيكي المقرمش',
        description: 'Golden fried chicken breast fillet, lettuce, tomato, creamy cheddar sauce in a brioche bun',
        price: 130,
        category: 'Chicken Sandwiches',
      },
      {
        id: 'buf-4',
        name: 'FUE Campus Combo: Burger + Fries + Soft Drink',
        nameAr: 'كومبو وجبة الطلاب مع بطاطس وكانز',
        description: 'Single burger of choice with crispy french fries and a soft drink can',
        price: 175,
        category: 'Student Combos',
        isStudentDeal: true,
        isPopular: true,
      },
      {
        id: 'buf-5',
        name: 'Cheesy Jalapeño Fries',
        nameAr: 'بطاطس بالجبنة والهلابينو',
        description: 'Hot seasoned french fries drenched in melted cheddar cheese sauce and spicy jalapeño slices',
        price: 70,
        category: 'Loaded Fries & Sides',
        isSpicy: true,
      },
    ],
  },

  'fue-koshary-campus': {
    restaurantId: 'fue-koshary-campus',
    restaurantName: 'Koshary El Tahrir - FUE Food Court',
    currency: 'EGP',
    lastUpdated: '2026-09-14',
    note: 'FUE Student Food Court. Fast, affordable, and filling authentic Egyptian koshary.',
    categories: ['Koshary Boxes', 'Tajines (Baked Pasta)', 'Sides & Toppings', 'Desserts & Drinks'],
    items: [
      {
        id: 'kt-1',
        name: 'Tahrir Mega Box (كشري التحرير ميجا)',
        nameAr: 'علبة كشري التحرير ميجا',
        description: 'Rice, lentils, macaroni, chickpeas, crisp fried onions, spicy salsa, and homemade garlic da’ah',
        price: 65,
        category: 'Koshary Boxes',
        isPopular: true,
        isStudentDeal: true,
      },
      {
        id: 'kt-2',
        name: 'Tahrir Regular Box (كشري كلاسيك)',
        nameAr: 'علبة كشري وسط',
        description: 'Standard student portion with all classic toppings and sauce packets',
        price: 50,
        category: 'Koshary Boxes',
        isVegetarian: true,
      },
      {
        id: 'kt-3',
        name: 'Minced Meat Pasta Tajine (طاجن مكرونة باللحمة)',
        nameAr: 'طاجن فرن مكرونة باللحمة المفرومة',
        description: 'Oven-baked penne pasta with spiced minced beef and rich tomato sauce',
        price: 80,
        category: 'Tajines (Baked Pasta)',
        isPopular: true,
      },
      {
        id: 'kt-4',
        name: 'Spicy Liver Pasta Tajine (طاجن فرن بالكبذة الإسكندراني)',
        nameAr: 'طاجن مكرونة بالكبذة الحارة',
        description: 'Oven-baked pasta with spicy Alexandrian beef liver and green peppers',
        price: 85,
        category: 'Tajines (Baked Pasta)',
        isSpicy: true,
      },
      {
        id: 'kt-5',
        name: 'Rice Pudding with Nuts (أرز باللبن بالمكسرات)',
        nameAr: 'أرز باللبن بالمكسرات والقشطة',
        description: 'Chilled creamy Egyptian rice pudding topped with raisins, coconut, and crushed hazelnuts',
        price: 35,
        category: 'Desserts & Drinks',
      },
    ],
  },

  'fue-dunkin-campus': {
    restaurantId: 'fue-dunkin-campus',
    restaurantName: "Dunkin' - FUE Campus Plaza",
    currency: 'EGP',
    lastUpdated: '2026-09-14',
    note: 'FUE Student Plaza. Grab-and-go donuts, iced coffee, and breakfast sandwiches.',
    categories: ['Fresh Donuts', 'Hot Coffee & Espresso', 'Iced Coffee & Refreshers', 'Savory Sandwiches'],
    items: [
      {
        id: 'dnk-1',
        name: 'Boston Kreme Donut',
        nameAr: 'دونت بوسطن كريم',
        description: 'Yeast donut filled with Bavarian cream and topped with rich chocolate icing',
        price: 45,
        category: 'Fresh Donuts',
        isPopular: true,
      },
      {
        id: 'dnk-2',
        name: 'Box of 6 Assorted Donuts',
        nameAr: 'علبة 6 دونتس مشكلة',
        description: 'Pick any 6 donuts: Glazed, Choco Frosted, Strawberry Sprinkle, Lotus, Boston Kreme',
        price: 240,
        category: 'Fresh Donuts',
        isPopular: true,
      },
      {
        id: 'dnk-3',
        name: 'Iced Dunkin’ Caramel Coffee (Medium)',
        nameAr: 'قهوة دانكن مثلجة بالكراميل',
        description: 'Signature iced brewed coffee with caramel swirl and cream over ice',
        price: 75,
        category: 'Iced Coffee & Refreshers',
        isStudentDeal: true,
        isPopular: true,
      },
      {
        id: 'dnk-4',
        name: 'Egg & Cheddar Croissant Sandwich',
        nameAr: 'ساندوتش كرواسون بيض وجبنة شيدر',
        description: 'Warm fluffy egg patty and melted cheddar cheese in a toasted croissant',
        price: 70,
        category: 'Savory Sandwiches',
      },
      {
        id: 'dnk-5',
        name: 'Hot Caramel Macchiato',
        nameAr: 'كراميل ماكياتو ساخن',
        description: 'Layered espresso with steamed milk and sweet caramel drizzle',
        price: 80,
        category: 'Hot Coffee & Espresso',
      },
    ],
  },

  'fue-central-cafeteria': {
    restaurantId: 'fue-central-cafeteria',
    restaurantName: 'FUE Central Cafeteria & Grill',
    currency: 'EGP',
    lastUpdated: '2026-09-14',
    note: 'FUE Main Student Building (Ground Floor). Daily home-style cooked meals and student lunch trays.',
    categories: ['Daily Lunch Meals', 'Grill & Shawarma', 'Sandwiches', 'Fresh Juices & Salads'],
    items: [
      {
        id: 'fcc-1',
        name: 'Grilled Shish Tawook Plate Meal',
        nameAr: 'وجبة شيش طاووق مشوي مع أرز وبطاطس',
        description: 'Tender marinated chicken breast cubes on skewers, served with basmati rice, french fries, garlic dip, and baladi bread',
        price: 135,
        category: 'Daily Lunch Meals',
        isPopular: true,
        isStudentDeal: true,
      },
      {
        id: 'fcc-2',
        name: 'Crispy Chicken Escalope Pane Meal',
        nameAr: 'وجبة فراخ بانيه مقرمشة',
        description: 'Golden breaded chicken cutlets with red sauce spaghetti, green salad, and tahini',
        price: 130,
        category: 'Daily Lunch Meals',
        isPopular: true,
      },
      {
        id: 'fcc-3',
        name: 'Chicken Shawarma Arabic Plate',
        nameAr: 'وجبة شاورما دجاج عربي مقطعة',
        description: 'Slices of spiced chicken shawarma in toasted saj bread, cut into rolls with garlic dip, pickles, and fries',
        price: 110,
        category: 'Grill & Shawarma',
        isPopular: true,
      },
      {
        id: 'fcc-4',
        name: 'Baladi Kofta Sandwich Roll',
        nameAr: 'ساندوتش كفتة بلدي طحينة وسلطة',
        description: 'Charcoal-grilled minced beef kofta with chopped parsley, tomatoes, and sesame tahini',
        price: 60,
        category: 'Sandwiches',
      },
      {
        id: 'fcc-5',
        name: 'Fresh Orange Juice (Large)',
        nameAr: 'عصير برتقال طبيعي فريش',
        description: '100% freshly squeezed natural Egyptian oranges with no added sugar',
        price: 45,
        category: 'Fresh Juices & Salads',
      },
    ],
  },

  'fue-container-campus': {
    restaurantId: 'fue-container-campus',
    restaurantName: 'Container Cafe - FUE Campus Yard',
    currency: 'EGP',
    lastUpdated: '2026-09-14',
    note: 'FUE Open Air Campus Yard. Specialty beans, cold brews, and artisan desserts.',
    categories: ['Specialty Coffee', 'Signature Cold Brews', 'Pastries & Waffles', 'Refreshers'],
    items: [
      {
        id: 'cnt-1',
        name: 'Double Shot Spanish Latte',
        nameAr: 'سبانيش لاتيه دبل شوت',
        description: 'Double espresso shot with creamy sweetened milk over crushed ice',
        price: 90,
        category: 'Specialty Coffee',
        isPopular: true,
      },
      {
        id: 'cnt-2',
        name: 'Nitro Cold Brew Coffee',
        nameAr: 'نيترو كولد برو كوفي',
        description: 'Slow-steeped 18-hour cold brew infused with nitrogen for a velvety smooth foam head',
        price: 95,
        category: 'Signature Cold Brews',
      },
      {
        id: 'cnt-3',
        name: 'Nutella & Pistachio Bubble Waffle',
        nameAr: 'وافل نوتيلا وفستق',
        description: 'Freshly pressed bubble waffle drenched in warm Nutella and crushed Iranian pistachios',
        price: 110,
        category: 'Pastries & Waffles',
        isPopular: true,
      },
      {
        id: 'cnt-4',
        name: 'Iced Hibiscus & Pomegranate Fizz',
        nameAr: 'كركديه بالرمان والليمون الفوار',
        description: 'Chilled steeped natural hibiscus flower with pomegranate juice and sparkling water',
        price: 60,
        category: 'Refreshers',
        isStudentDeal: true,
      },
    ],
  },

  'fue-tabio-campus': {
    restaurantId: 'fue-tabio-campus',
    restaurantName: 'TABiO Tea & Boba - FUE Campus',
    currency: 'EGP',
    lastUpdated: '2026-09-14',
    note: 'FUE Pharmacy Building Promenade. Authentic tapioca boba pearls and brewed milk teas.',
    categories: ['Boba Milk Teas', 'Fruit Teas & Popping Boba', 'Specialty Matcha', 'Snacks'],
    items: [
      {
        id: 'tb-1',
        name: 'Brown Sugar Tiger Milk Boba',
        nameAr: 'تايجر ميلك تي بالسكر البني وبوبا',
        description: 'Warm brown sugar tapioca pearls with organic fresh milk and caramelized stripes',
        price: 110,
        category: 'Boba Milk Teas',
        isPopular: true,
      },
      {
        id: 'tb-2',
        name: 'Taro Milk Tea with Tapioca Pearls',
        nameAr: 'تارو ميلك تي بالبوبا',
        description: 'Creamy purple taro tea with chewy slow-cooked honey boba',
        price: 105,
        category: 'Boba Milk Teas',
        isPopular: true,
      },
      {
        id: 'tb-3',
        name: 'Passion Fruit Mango Green Tea with Mango Popping Boba',
        nameAr: 'شاي أخضر باشن فروت ومانجو مع بوبا بوبينج',
        description: 'Jasmine green tea infused with passion fruit and real mango juice with popping juice boba',
        price: 95,
        category: 'Fruit Teas & Popping Boba',
        isStudentDeal: true,
      },
      {
        id: 'tb-4',
        name: 'Matcha Strawberry Milk Layered Latte',
        nameAr: 'ماتشا بالفراولة والحليب',
        description: 'Crushed strawberry puree layered with fresh milk and ceremonial matcha whisked on top',
        price: 125,
        category: 'Specialty Matcha',
      },
    ],
  },

  'fue-shaghaf-campus': {
    restaurantId: 'fue-shaghaf-campus',
    restaurantName: 'Shaghaf Cafe & Study Corner',
    currency: 'EGP',
    lastUpdated: '2026-09-14',
    note: 'FUE Library Annex. Quiet study atmosphere, high-speed WiFi, and study fuel snacks.',
    categories: ['Espresso & Coffee', 'Herbal Teas', 'Study Fuel Snacks', 'Fresh Juices'],
    items: [
      {
        id: 'shg-1',
        name: 'Exam Fuel: Flat White (Double Shot)',
        nameAr: 'فلات وايت دبل إسبريسو',
        description: 'Velvety micro-foamed milk with double ristretto shots for deep focus',
        price: 80,
        category: 'Espresso & Coffee',
        isPopular: true,
      },
      {
        id: 'shg-2',
        name: 'Turkey & Cheddar Panini with Chips',
        nameAr: 'بانيني تركي وشيدر ساخن',
        description: 'Pressed hot sandwich with smoked turkey, cheddar, and Dijon mustard',
        price: 85,
        category: 'Study Fuel Snacks',
        isStudentDeal: true,
      },
      {
        id: 'shg-3',
        name: 'Lemon Mint Detox Chiller',
        nameAr: 'ليمون نعناع فريش مثلج',
        description: 'Freshly blended lemon with garden mint leaves and crushed ice',
        price: 50,
        category: 'Fresh Juices',
      },
      {
        id: 'shg-4',
        name: 'Nutella Waffle with Vanilla Ice Cream',
        nameAr: 'وافل نوتيلا مع بولة آيس كريم',
        description: 'Warm crisp waffle topped with rich Nutella spread and a scoop of vanilla gelato',
        price: 90,
        category: 'Study Fuel Snacks',
      },
    ],
  },

  'fue-sugo': {
    restaurantId: 'fue-sugo',
    restaurantName: 'Sugo (سوجو) - FUE Food Court',
    currency: 'EGP',
    lastUpdated: '2026-09-14',
    note: 'FUE Student Food Court. Authentic Egyptian street food & oriental sandwiches made fresh to order.',
    categories: ['شرقي', 'الإضافات', 'الحلو', 'المشروبات'],
    items: [
      // ─── شرقي ───────────────────────────────────────────
      {
        id: 'sug-1',
        name: 'Classic Hawawshi',
        nameAr: 'حواوشي كلاسيك',
        description: 'Egyptian baladi bread stuffed with seasoned minced meat baked to crispy golden perfection',
        price: 70,
        category: 'شرقي',
        isPopular: true,
      },
      {
        id: 'sug-2',
        name: 'Cheese Hawawshi',
        nameAr: 'حواوشي بالجبنة',
        description: 'Crispy hawawshi loaded with melted mozzarella and cheddar cheese blend',
        price: 80,
        category: 'شرقي',
        isPopular: true,
        isStudentDeal: true,
      },
      {
        id: 'sug-3',
        name: 'Alexandrian Kebda',
        nameAr: 'كبدة اسكندراني',
        description: 'Fresh beef liver sautéed with garlic, hot chili peppers, cumin, and lemon in fresh fino',
        price: 35,
        category: 'شرقي',
        isSpicy: true,
        isPopular: true,
      },
      {
        id: 'sug-4',
        name: 'Alexandrian Sujuk',
        nameAr: 'سجق اسكندراني',
        description: 'Savory Alexandrian sausage with fresh peppers, onions, tomatoes, and spiced garlic sauce',
        price: 35,
        category: 'شرقي',
        isSpicy: true,
      },
      {
        id: 'sug-5',
        name: 'Oriental Sujuk',
        nameAr: 'سجق شرقي',
        description: 'Traditional Egyptian spiced sausage grilled and seasoned with secret spices',
        price: 35,
        category: 'شرقي',
        isPopular: true,
      },
      {
        id: 'sug-6',
        name: 'Shish Tawook Sandwich',
        nameAr: 'شيش طاووق',
        description: 'Marinated juicy grilled chicken chunks with peppers, onions, and garlic toum sauce',
        price: 65,
        category: 'شرقي',
        isStudentDeal: true,
      },
      {
        id: 'sug-7',
        name: 'Grilled Kofta Sandwich',
        nameAr: 'كفتة',
        description: 'Charcoal-grilled seasoned minced beef kofta with tahini and fresh parsley',
        price: 65,
        category: 'شرقي',
        isPopular: true,
      },
      {
        id: 'sug-8',
        name: 'Rice with Kebda Plate',
        nameAr: 'رز بالكبدة',
        description: 'Egyptian spiced golden rice topped with sizzling Alexandrian beef liver',
        price: 90,
        category: 'شرقي',
      },
      {
        id: 'sug-9',
        name: 'Rice with Sujuk Plate',
        nameAr: 'رز بالسجق',
        description: 'Egyptian seasoned rice served with generous savory oriental sujuk cuts',
        price: 90,
        category: 'شرقي',
      },
      {
        id: 'sug-10',
        name: 'Pasta with Kebda Plate',
        nameAr: 'مكرونة بالكبدة',
        description: 'Penne pasta tossed in rich tomato sauce topped with Alexandrian spicy liver',
        price: 90,
        category: 'شرقي',
        isSpicy: true,
      },
      {
        id: 'sug-11',
        name: 'Pasta with Sujuk Plate',
        nameAr: 'مكرونة بالسجق',
        description: 'Penne pasta in seasoned red sauce topped with sizzling spiced oriental sausage',
        price: 90,
        category: 'شرقي',
      },

      // ─── الإضافات ─────────────────────────────────────────
      {
        id: 'sug-12',
        name: 'Spiced Fries (Batates Bel Kholta)',
        nameAr: 'بطاطس بالخلطة',
        description: 'Golden crispy french fries tossed in special Sugo herb and spice seasoning blend',
        price: 25,
        category: 'الإضافات',
        isVegetarian: true,
        isPopular: true,
      },
      {
        id: 'sug-13',
        name: 'Pickled Tomatoes (Tomatem Mekhalela)',
        nameAr: 'طماطم مخللة',
        description: 'Fresh ripe tomatoes marinated in garlic, vinegar, cumin, fresh herbs, and lemon',
        price: 25,
        category: 'الإضافات',
        isVegetarian: true,
      },
      {
        id: 'sug-14',
        name: 'Egyptian Pickles (Mekhalel)',
        nameAr: 'مخلل',
        description: 'Traditional mixed Egyptian pickled cucumbers, carrots, and turnip',
        price: 15,
        category: 'الإضافات',
        isVegetarian: true,
      },

      // ─── الحلو ──────────────────────────────────────────
      {
        id: 'sug-15',
        name: 'Halawa Sandwich',
        nameAr: 'حلاوة سادة',
        description: 'Sweet sesame tahini halawa spread in warm fresh fino bread',
        price: 25,
        category: 'الحلو',
        isVegetarian: true,
      },
      {
        id: 'sug-16',
        name: 'Jam Sandwich (Moraba)',
        nameAr: 'مربى',
        description: 'Fruity strawberry jam with creamy eshta cream in fresh bread',
        price: 30,
        category: 'الحلو',
        isVegetarian: true,
      },
      {
        id: 'sug-17',
        name: 'Sakallans (Halawa, Jam & Eshta)',
        nameAr: 'سكلانس',
        description: 'The legendary Egyptian dessert sandwich loaded with halawa, sweet jam, honey, and rich fresh eshta',
        price: 40,
        category: 'الحلو',
        isPopular: true,
        isStudentDeal: true,
      },

      // ─── المشروبات ───────────────────────────────────────
      {
        id: 'sug-18',
        name: 'Red Bull Energy Drink',
        nameAr: 'ريد بول',
        description: 'Chilled 250ml Red Bull energy can',
        price: 70,
        category: 'المشروبات',
      },
      {
        id: 'sug-19',
        name: 'Soft Drink (Haga Saa\'a)',
        nameAr: 'حاجة ساقعة',
        description: 'Chilled can of soda (Pepsi, Coca-Cola, 7Up, or Miranda)',
        price: 20,
        category: 'المشروبات',
      },
      {
        id: 'sug-20',
        name: 'Enab (Hibiscus Iced Drink)',
        nameAr: 'عناب',
        description: 'Refreshing traditional chilled sweet Egyptian karkadeh hibiscus drink',
        price: 40,
        category: 'المشروبات',
        isPopular: true,
      },
      {
        id: 'sug-21',
        name: 'Mineral Water',
        nameAr: 'مياه معدنية',
        description: 'Chilled bottle of pure mineral water',
        price: 10,
        category: 'المشروبات',
      },
    ],
  },

  'fue-bw-burger': {
    restaurantId: 'fue-bw-burger',
    restaurantName: 'B&W (Burgers & Wings) - FUE Food Court',
    currency: 'EGP',
    lastUpdated: '2026-09-14',
    note: 'FUE Student Food Court. Smash beef burgers, tossed crispy wings, fried & grilled chicken sandwiches, and creamy pastas.',
    categories: [
      'BEEF BURGERS',
      'SAUSAGE',
      'FRIED CHICKEN WINGS (BONE-IN)',
      'PASTA',
      'SALAD',
      'FRIED CHICKEN SANDWICHES',
      'GRILLED CHICKEN SANDWICHES',
      'FRIED CHICKEN STRIPS',
      'SNACKS',
      'SOFT DRINK',
    ],
    items: [
      // ─── BEEF BURGERS ───────────────────────────────────
      {
        id: 'bw-1',
        name: 'CLASSIC BURGER',
        nameAr: 'كلاسيك برجر',
        description: 'Juicy 100% prime beef patty with lettuce, fresh tomatoes, pickles, and signature B&W sauce on a brioche bun',
        price: 100,
        category: 'BEEF BURGERS',
        isPopular: true,
      },
      {
        id: 'bw-2',
        name: 'CHEESE BURGER',
        nameAr: 'تشيز برجر',
        description: 'Prime beef patty topped with melted American cheddar cheese, lettuce, tomatoes, and secret sauce',
        price: 110,
        category: 'BEEF BURGERS',
        isPopular: true,
        isStudentDeal: true,
      },
      {
        id: 'bw-3',
        name: 'BBQ BURGER',
        nameAr: 'بي بي كيو برجر',
        description: 'Flame-seared beef patty smothered in rich smoky BBQ sauce with crisp caramelized onion rings and cheese',
        price: 110,
        category: 'BEEF BURGERS',
      },
      {
        id: 'bw-4',
        name: 'MUSHROOM BURGER',
        nameAr: 'مشروم برجر',
        description: 'Beef patty topped with creamy sautéed button mushrooms and melted Swiss cheese',
        price: 115,
        category: 'BEEF BURGERS',
        isPopular: true,
      },
      {
        id: 'bw-5',
        name: 'CHILI BEEF BURGER',
        nameAr: 'تشيلي بيف برجر',
        description: 'Spicy chili-infused beef burger with jalapenos, cheddar sauce, and zesty chili dressing',
        price: 115,
        category: 'BEEF BURGERS',
        isSpicy: true,
      },
      {
        id: 'bw-6',
        name: 'FIRE BURGER',
        nameAr: 'فاير برجر',
        description: 'Extra fiery beef burger with hot pepper relish, sriracha fire sauce, and pepper jack cheese',
        price: 115,
        category: 'BEEF BURGERS',
        isSpicy: true,
      },

      // ─── SAUSAGE ─────────────────────────────────────────
      {
        id: 'bw-7',
        name: 'BBQ SAUSAGE',
        nameAr: 'سوسيس بي بي كيو',
        description: 'Grilled specialty sausage drenched in sweet & smoky BBQ sauce in a warm toasted sub',
        price: 95,
        category: 'SAUSAGE',
      },
      {
        id: 'bw-8',
        name: 'CLASSIC SAUSAGE',
        nameAr: 'سوسيس كلاسيك',
        description: 'Traditional grilled seasoned sausage with mustard, relish, and melted cheese',
        price: 85,
        category: 'SAUSAGE',
        isStudentDeal: true,
      },

      // ─── FRIED CHICKEN WINGS (BONE-IN) ───────────────────
      {
        id: 'bw-9',
        name: 'FRIED CHICKEN WINGS (BONE-IN)',
        nameAr: 'أجنحة دجاج مقلية (بالعظم)',
        description: 'Crispy bone-in chicken wings tossed in your choice of special sauces (Fire, Buffalo, Honey Chili, BBQ, or Sweet); served with cool ranch dip',
        price: 120,
        category: 'FRIED CHICKEN WINGS (BONE-IN)',
        isPopular: true,
      },

      // ─── PASTA ───────────────────────────────────────────
      {
        id: 'bw-10',
        name: 'MAC CHEESE',
        nameAr: 'ماك آند تشيز',
        description: 'Creamy macaroni baked in rich golden three-cheese blend (Add Grilled or Fried Chicken +50 LE)',
        price: 60,
        category: 'PASTA',
        isVegetarian: true,
      },
      {
        id: 'bw-11',
        name: 'ALFREDO PASTA',
        nameAr: 'مكرونة ألفريدو',
        description: 'Fettuccine pasta in rich velvety parmesan white cream sauce with garlic & herbs (Add Grilled or Fried Chicken +50 LE)',
        price: 70,
        category: 'PASTA',
        isPopular: true,
      },
      {
        id: 'bw-12',
        name: 'BASIL PASTA',
        nameAr: 'مكرونة بالريحان والبيستو',
        description: 'Penne pasta tossed in aromatic Italian basil pesto cream sauce (Add Grilled or Fried Chicken +50 LE)',
        price: 60,
        category: 'PASTA',
        isVegetarian: true,
      },

      // ─── SALAD ───────────────────────────────────────────
      {
        id: 'bw-13',
        name: 'CAESAR SALAD',
        nameAr: 'سلطة سيزر',
        description: 'Crisp romaine lettuce, toasted garlic croutons, and grated parmesan cheese with Caesar dressing (Add Grilled or Fried Chicken +50 LE)',
        price: 80,
        category: 'SALAD',
        isVegetarian: true,
      },
      {
        id: 'bw-14',
        name: 'RANCH SALAD',
        nameAr: 'سلطة رانش',
        description: 'Fresh garden greens, cherry tomatoes, sweet corn, and cucumbers drizzled with buttermilk ranch dressing (Add Grilled or Fried Chicken +50 LE)',
        price: 70,
        category: 'SALAD',
        isVegetarian: true,
      },

      // ─── FRIED CHICKEN SANDWICHES ────────────────────────
      {
        id: 'bw-15',
        name: 'CLASSIC FRIED CHICKEN',
        nameAr: 'كلاسيك فرايد تشيكن',
        description: 'Golden crispy chicken breast fillet with lettuce, pickles, and mayo on a toasted bun',
        price: 100,
        category: 'FRIED CHICKEN SANDWICHES',
        isPopular: true,
      },
      {
        id: 'bw-16',
        name: 'BUFFALO CHICKEN',
        nameAr: 'بافلو تشيكن',
        description: 'Crispy chicken drenched in spicy tangy buffalo sauce topped with cool blue cheese ranch',
        price: 120,
        category: 'FRIED CHICKEN SANDWICHES',
        isSpicy: true,
      },
      {
        id: 'bw-17',
        name: 'BBQ RANCH CHICKEN',
        nameAr: 'بي بي كيو رانش تشيكن',
        description: 'Crunchy chicken fillet with sweet BBQ glaze, creamy ranch sauce, and melted cheddar',
        price: 110,
        category: 'FRIED CHICKEN SANDWICHES',
      },
      {
        id: 'bw-18',
        name: 'HONEY CHILI CHICKEN',
        nameAr: 'هاني تشيلي تشيكن',
        description: 'Crispy fried chicken glazed in sweet honey chili sauce with fresh lettuce and sesame',
        price: 120,
        category: 'FRIED CHICKEN SANDWICHES',
        isSpicy: true,
      },
      {
        id: 'bw-19',
        name: 'FIRE CHICKEN',
        nameAr: 'فاير تشيكن',
        description: 'Extra fiery spicy fried chicken with hot ghost pepper drizzle and jalapenos',
        price: 120,
        category: 'FRIED CHICKEN SANDWICHES',
        isSpicy: true,
      },
      {
        id: 'bw-20',
        name: 'ZINGER SANDWICH',
        nameAr: 'ساندوتش زنجر',
        description: 'Crunchy spiced zinger fillet with cheddar cheese slice, lettuce, and zesty sauce',
        price: 90,
        category: 'FRIED CHICKEN SANDWICHES',
        isPopular: true,
        isStudentDeal: true,
      },

      // ─── GRILLED CHICKEN SANDWICHES ──────────────────────
      {
        id: 'bw-21',
        name: 'CLASSIC GRILLED CHICKEN',
        nameAr: 'كلاسيك جريلد تشيكن',
        description: 'Tender marinated grilled chicken breast with lettuce, tomato, and herb garlic spread',
        price: 100,
        category: 'GRILLED CHICKEN SANDWICHES',
      },
      {
        id: 'bw-22',
        name: 'LOADED GRILLED CHICKEN',
        nameAr: 'لودد جريلد تشيكن',
        description: 'Herb-grilled chicken breast loaded with sautéed mushrooms, melted cheese, and caramelized onions',
        price: 120,
        category: 'GRILLED CHICKEN SANDWICHES',
        isPopular: true,
      },
      {
        id: 'bw-23',
        name: 'FIRE GRILLED CHICKEN',
        nameAr: 'فاير جريلد تشيكن',
        description: 'Grilled chicken breast seasoned with fiery spices, chipotle sauce, and spicy salsa',
        price: 120,
        category: 'GRILLED CHICKEN SANDWICHES',
        isSpicy: true,
      },

      // ─── FRIED CHICKEN STRIPS ────────────────────────────
      {
        id: 'bw-24',
        name: 'FRIED CHICKEN STRIPS',
        nameAr: 'ستريبس دجاج مقلية مقرمشة',
        description: 'Golden fried chicken tenders tossed in your choice of sauce (Classic, Fire, Buffalo, Honey Chili, or BBQ); served with ranch sauce',
        price: 120,
        category: 'FRIED CHICKEN STRIPS',
        isPopular: true,
      },

      // ─── SNACKS ──────────────────────────────────────────
      {
        id: 'bw-25',
        name: 'FRENCH FRIES',
        nameAr: 'بطاطس مقلية',
        description: 'Crispy salted golden french fries',
        price: 30,
        category: 'SNACKS',
        isVegetarian: true,
      },
      {
        id: 'bw-26',
        name: 'CHEESY FRIES',
        nameAr: 'تشيزي فرايز',
        description: 'Crisp french fries drenched in warm melted cheddar cheese sauce',
        price: 40,
        category: 'SNACKS',
        isVegetarian: true,
        isPopular: true,
      },
      {
        id: 'bw-27',
        name: 'HOT FRIES',
        nameAr: 'هوت فرايز حارة',
        description: 'Spiced hot fries tossed with spicy seasoning and jalapeño slices',
        price: 40,
        category: 'SNACKS',
        isSpicy: true,
        isVegetarian: true,
      },
      {
        id: 'bw-28',
        name: 'CHILI CHEESE FRIES',
        nameAr: 'تشيلي تشيز فرايز',
        description: 'Loaded fries topped with savory minced beef chili sauce and melted cheddar',
        price: 75,
        category: 'SNACKS',
        isSpicy: true,
      },

      // ─── SOFT DRINK ──────────────────────────────────────
      {
        id: 'bw-29',
        name: 'SOFT DRINK',
        nameAr: 'مشروب غازي',
        description: 'Chilled soda can (Pepsi, 7Up, Miranda, Diet Pepsi)',
        price: 20,
        category: 'SOFT DRINK',
      },
      {
        id: 'bw-30',
        name: 'WATER',
        nameAr: 'مياه معدنية',
        description: 'Chilled pure mineral water bottle',
        price: 10,
        category: 'SOFT DRINK',
      },
    ],
  },

  'fue-bimbo': {
    restaurantId: 'fue-bimbo',
    restaurantName: 'Bimbo - FUE Food Court & Plaza',
    currency: 'EGP',
    lastUpdated: '2026-09-14',
    note: 'FUE Student Food Court Kiosk. Fresh Belgian waffles, sweet & savory crepes, soft serve ice cream, and loaded milkshakes.',
    categories: ['Waffles & Pancakes', 'Sweet & Savory Crepes', 'Ice Cream & Gelato', 'Shakes & Cold Drinks'],
    items: [
      {
        id: 'bim-1',
        name: 'Nutella Waffle with Banana & Nuts',
        nameAr: 'وافل نوتيلا بالموز والمكسرات',
        description: 'Crispy Belgian waffle coated with warm Nutella spread, fresh banana slices, and crushed hazelnuts',
        price: 85,
        category: 'Waffles & Pancakes',
        isPopular: true,
        isVegetarian: true,
      },
      {
        id: 'bim-2',
        name: 'Lotus Biscoff Crepe Roll',
        nameAr: 'كريب لوتس بسكوف',
        description: 'Thin French crepe filled and drizzled with melted Lotus butter and crushed Biscoff crumbs',
        price: 90,
        category: 'Sweet & Savory Crepes',
        isPopular: true,
        isStudentDeal: true,
        isVegetarian: true,
      },
      {
        id: 'bim-3',
        name: 'Crispy Chicken & Mozzarella Crepe',
        nameAr: 'كريب زنجر دجاج مقرمش وموزاريلا',
        description: 'Crispy fried chicken tenders with mozzarella, bell peppers, olives, and BBQ ranch inside a toasted crepe',
        price: 95,
        category: 'Sweet & Savory Crepes',
        isPopular: true,
      },
      {
        id: 'bim-4',
        name: 'Oreo Madness Milkshake',
        nameAr: 'ميلك شيك أوريو بالكريمة',
        description: 'Blended vanilla gelato and crushed Oreo cookies topped with whipped cream and chocolate drizzle',
        price: 65,
        category: 'Shakes & Cold Drinks',
        isPopular: true,
        isVegetarian: true,
      },
      {
        id: 'bim-5',
        name: 'Double Scoop Gelato Cone',
        nameAr: 'آيس كريم بولتين في بسكوت وافل',
        description: 'Two scoops of artisan Italian gelato (Chocolate, Pistachio, Strawberry, Mango, or Salted Caramel)',
        price: 50,
        category: 'Ice Cream & Gelato',
        isVegetarian: true,
      },
      {
        id: 'bim-6',
        name: 'Fudge Brownie Sundae Bowl',
        nameAr: 'صنداي براونيز فادج بالشوكولاتة',
        description: 'Warm chocolate fudge brownie cubes with vanilla soft serve, hot chocolate fudge, and roasted peanuts',
        price: 75,
        category: 'Ice Cream & Gelato',
        isVegetarian: true,
      },
      {
        id: 'bim-7',
        name: 'Iced Frappé Choco-Caramel',
        nameAr: 'فرابتشينو شوكو كراميل مثلج',
        description: 'Chilled blended iced coffee with caramel swirls, chocolate chips, and sweet cream',
        price: 60,
        category: 'Shakes & Cold Drinks',
      },
    ],
  },

  'fue-abou-shakra-campus': {
    restaurantId: 'fue-abou-shakra-campus',
    restaurantName: 'Abou Shakra Express - FUE Food Court',
    currency: 'EGP',
    lastUpdated: '2026-09-14',
    note: 'FUE Student Food Court. Authentic Egyptian charcoal grills, kofta sandwiches, and oriental platters.',
    categories: ['Sandwiches & Rolls', 'Grill Platters', 'Sides & Salads', 'Drinks'],
    items: [
      {
        id: 'abk-1',
        name: 'Charcoal Kofta Sandwich Roll',
        nameAr: 'ساندوتش كفتة مشوية على الفحم',
        description: 'Juicy spiced minced beef kofta skewer grilled over charcoal in fresh baladi bread with tahini',
        price: 75,
        category: 'Sandwiches & Rolls',
        isPopular: true,
        isStudentDeal: true,
      },
      {
        id: 'abk-2',
        name: 'Shish Tawook Sandwich',
        nameAr: 'ساندوتش شيش طاووق',
        description: 'Marinated grilled chicken cubes with garlic dip (Toum) and pickles in Lebanese flatbread',
        price: 80,
        category: 'Sandwiches & Rolls',
        isPopular: true,
      },
      {
        id: 'abk-3',
        name: 'Mixed Grill Express Meal',
        nameAr: 'وجبة مشويات مشكلة إكسبريس',
        description: 'Kofta skewers and shish tawook served with yellow basmati rice, french fries, and green salad',
        price: 165,
        category: 'Grill Platters',
        isPopular: true,
      },
      {
        id: 'abk-4',
        name: 'Hawawshi Abou Shakra',
        nameAr: 'حواوشي أبو شقرة المميز',
        description: 'Crispy oven-baked baladi bread stuffed with seasoned beef, onions, and oriental spices',
        price: 70,
        category: 'Sandwiches & Rolls',
      },
      {
        id: 'abk-5',
        name: 'Tahini & Baba Ghanoush Dip Duo',
        nameAr: 'طحينة وبابا غنوج مع عيش بلدي',
        description: 'Fresh sesame tahini and smoked eggplant dip served with 2 warm baladi breads',
        price: 35,
        category: 'Sides & Salads',
        isVegetarian: true,
      },
    ],
  },

  'fue-coffeeshop-company': {
    restaurantId: 'fue-coffeeshop-company',
    restaurantName: 'Coffeeshop Company - FUE Campus',
    currency: 'EGP',
    lastUpdated: '2026-09-14',
    note: 'FUE Campus Gate 1 Plaza. Austrian specialty coffees, sandwiches, and European pastries.',
    categories: ['Specialty Coffee & Espresso', 'Iced & Blended Drinks', 'Paninis & Bagels', 'Bakery'],
    items: [
      {
        id: 'csc-1',
        name: 'Viennese Melange Coffee',
        nameAr: 'فينيس ميلانج كلاسيك',
        description: 'Traditional Austrian specialty coffee topped with velvety steamed milk froth and chocolate dust',
        price: 90,
        category: 'Specialty Coffee & Espresso',
        isPopular: true,
      },
      {
        id: 'csc-2',
        name: 'Roast Beef & Cheddar Ciabatta',
        nameAr: 'ساندوتش روست بيف وشيدر في خبز تشاباتا',
        description: 'Tender sliced roast beef, aged cheddar, arugula, and Dijon mustard on toasted Italian ciabatta',
        price: 120,
        category: 'Paninis & Bagels',
        isPopular: true,
        isStudentDeal: true,
      },
      {
        id: 'csc-3',
        name: 'Iced Caramel Macchiato',
        nameAr: 'كاراميل ماكياتو مثلج',
        description: 'Double espresso shots layered with cold milk and sweet Austrian caramel sauce over ice',
        price: 95,
        category: 'Iced & Blended Drinks',
        isPopular: true,
      },
      {
        id: 'csc-4',
        name: 'Smoked Salmon Bagel',
        nameAr: 'بيجل سلمون مدخن بالجبنة الكريمية',
        description: 'Toasted sesame bagel with Norwegian smoked salmon, cream cheese, capers, and dill',
        price: 145,
        category: 'Paninis & Bagels',
      },
      {
        id: 'csc-5',
        name: 'Warm Apple Strudel with Cream',
        nameAr: 'أبل سترودل نمساوي بالتفاح والقرفة',
        description: 'Authentic Viennese layered pastry stuffed with spiced apples, raisins, and vanilla cream',
        price: 85,
        category: 'Bakery',
        isVegetarian: true,
      },
    ],
  },
  'fue-costa-campus': {
    restaurantId: 'fue-costa-campus',
    restaurantName: 'Costa Coffee - FUE Campus',
    currency: 'EGP',
    lastUpdated: '2026-09-14',
    note: 'Located at FUE Engineering Plaza & Library Walk. Premium handcrafted espresso, frostinos, and fresh toasties.',
    categories: ['Espresso & Hot Coffee', 'Iced & Frostinos', 'Toasties & Sandwiches', 'Bakery & Sweet Treats'],
    items: [
      {
        id: 'cst-1',
        name: 'Signature Flat White',
        nameAr: 'فلات وايت كوستـا كلاسيك',
        description: 'Rich Cortissimo espresso blend with velvety, textured whole milk micro-foam',
        price: 90,
        category: 'Espresso & Hot Coffee',
        isPopular: true,
      },
      {
        id: 'cst-2',
        name: 'Iced Spanish Latte',
        nameAr: 'سبانيش لاتيه مثلج',
        description: 'Double espresso pulled over chilled sweetened condensed milk and fresh cold milk',
        price: 95,
        category: 'Iced & Frostinos',
        isPopular: true,
        isStudentDeal: true,
      },
      {
        id: 'cst-3',
        name: 'Salted Caramel Crunch Frostino',
        nameAr: 'فروسـتينو كراميل مملح وكرانش',
        description: 'Blended creamy ice beverage topped with whipped cream, rich caramel drizzle, and crunchy crunchies',
        price: 105,
        category: 'Iced & Frostinos',
        isPopular: true,
      },
      {
        id: 'cst-4',
        name: 'Roast Beef & Cheddar Melt Toastie',
        nameAr: 'توست روست بيف وشيدر ساخن',
        description: 'Slices of roast beef, melted mature cheddar, and tangy whole grain mustard on toasted sourdough',
        price: 115,
        category: 'Toasties & Sandwiches',
        isStudentDeal: true,
      },
      {
        id: 'cst-5',
        name: 'Three Cheese & Tomato Focaccia',
        nameAr: 'فوكاشيا ثلاث أجبان وطماطم',
        description: 'Melted mozzarella, cheddar, and gouda with sun-ripened tomatoes on fresh rosemary focaccia',
        price: 90,
        category: 'Toasties & Sandwiches',
        isVegetarian: true,
      },
      {
        id: 'cst-6',
        name: 'Warm Rich Chocolate Fudge Muffin',
        nameAr: 'مافن شوكولاتة فدج دافئ',
        description: 'Decadent chocolate muffin filled with molten fudge cream and Belgian chocolate chips',
        price: 65,
        category: 'Bakery & Sweet Treats',
        isPopular: true,
        isVegetarian: true,
      },
      {
        id: 'cst-7',
        name: 'Carrot & Walnut Cake Slice',
        nameAr: 'كيكة الجزر والجوز بالكريمة',
        description: 'Spiced carrot sponge with roasted walnuts and classic cream cheese frosting',
        price: 75,
        category: 'Bakery & Sweet Treats',
        isVegetarian: true,
      },
    ],
  },
  'fue-uncle-tonny': {
    restaurantId: 'fue-uncle-tonny',
    restaurantName: 'Uncle Tonny',
    currency: 'EGP',
    lastUpdated: '2026-09-14',
    note: 'Located at FUE Campus Food Court Main Plaza. Fresh smashed burgers, crispy chicken, and student combos.',
    categories: ['Burgers & Smash', 'Crispy Chicken & Strips', 'Loaded Fries & Appetizers', 'Combos & Drinks'],
    items: [
      {
        id: 'tonny-1',
        name: 'Uncle Tonny Double Smash Burger',
        nameAr: 'أونكل توني دوبل سماش برجر',
        description: 'Two smashed premium beef patties with American cheese, pickles, caramelized onions, and signature Tonny sauce',
        price: 140,
        category: 'Burgers & Smash',
        isPopular: true,
      },
      {
        id: 'tonny-2',
        name: 'Classic Cheeseburger',
        nameAr: 'كلاسيك تشيز برجر',
        description: 'Single smashed beef patty with melted cheese, lettuce, fresh tomato, and secret burger sauce',
        price: 105,
        category: 'Burgers & Smash',
      },
      {
        id: 'tonny-3',
        name: 'Crispy Chicken Tender Wrap',
        nameAr: 'راب تشيكن ستربس مقرمشة',
        description: 'Golden fried chicken tenders wrapped with lettuce, cheddar cheese, and honey mustard sauce',
        price: 95,
        category: 'Crispy Chicken & Strips',
        isPopular: true,
        isStudentDeal: true,
      },
      {
        id: 'tonny-4',
        name: 'Crispy Tenders Meal (3 Pcs + Fries + Dip)',
        nameAr: 'وجبة كرسبي تندرز (٣ قطع + بطاطس + صوص)',
        description: 'Three hand-breaded chicken tenders served with golden fries, coleslaw, and dipping sauce',
        price: 120,
        category: 'Crispy Chicken & Strips',
        isPopular: true,
        isStudentDeal: true,
      },
      {
        id: 'tonny-5',
        name: 'Tonny Cheesy Volcano Fries',
        nameAr: 'بطاطس تشيزي بركان أونكل توني',
        description: 'Crispy seasoned fries covered with melted cheddar cheese sauce and jalapeños',
        price: 65,
        category: 'Loaded Fries & Appetizers',
        isVegetarian: true,
      },
      {
        id: 'tonny-6',
        name: 'Onion Rings with Ranch Dip',
        nameAr: 'حلقات بصل مقرمشة مع صوص رانش',
        description: 'Crispy battered onion rings served with house-made ranch',
        price: 45,
        category: 'Loaded Fries & Appetizers',
        isVegetarian: true,
      },
      {
        id: 'tonny-7',
        name: 'Fresh Lemon Mint Juice',
        nameAr: 'ليمون بالنعناع فريش',
        description: 'Fresh squeezed lemon juice blended with garden mint over crushed ice',
        price: 40,
        category: 'Combos & Drinks',
      },
    ],
  },
  'fue-vivo': {
    restaurantId: 'fue-vivo',
    restaurantName: 'Vivo',
    currency: 'EGP',
    lastUpdated: '2026-09-14',
    note: 'Located at FUE Campus Food Court & Plaza. Artisanal Italian oven-baked pizzas, freshly tossed pasta, and paninis.',
    categories: ['Pizza', 'Pasta & Risotto', 'Paninis & Starters', 'Desserts & Beverages'],
    items: [
      {
        id: 'vivo-1',
        name: 'Pizza Margherita',
        nameAr: 'بيتزا مارجريتا نابوليتان',
        description: 'Traditional tomato sauce, fresh mozzarella Fior di Latte, basil leaves, and extra virgin olive oil',
        price: 95,
        category: 'Pizza',
        isPopular: true,
        isVegetarian: true,
      },
      {
        id: 'vivo-2',
        name: 'Pizza Pepperoni & Hot Honey',
        nameAr: 'بيتزا ببروني مع عسل حار',
        description: 'Crispy beef pepperoni slices, rich mozzarella, oregano, and a drizzle of hot chili honey',
        price: 130,
        category: 'Pizza',
        isPopular: true,
      },
      {
        id: 'vivo-3',
        name: 'Chicken Alfredo Fettuccine',
        nameAr: 'فيتوتشيني تشيكن ألفريدو',
        description: 'Tender grilled chicken strips with creamy parmesan mushroom Alfredo sauce over freshly cooked pasta',
        price: 115,
        category: 'Pasta & Risotto',
        isPopular: true,
        isStudentDeal: true,
      },
      {
        id: 'vivo-4',
        name: 'Penne all’Arrabbiata',
        nameAr: 'بيني أرابياتا حارة بالريحان',
        description: 'Spicy Italian garlic tomato sauce with crushed red pepper and fresh basil',
        price: 85,
        category: 'Pasta & Risotto',
        isVegetarian: true,
      },
      {
        id: 'vivo-5',
        name: 'Smoked Turkey & Mozzarella Panini',
        nameAr: 'بانيني تركي مدخن وموزاريلا',
        description: 'Toasted artisan ciabatta with smoked turkey, mozzarella, arugula, and pesto mayo',
        price: 85,
        category: 'Paninis & Starters',
        isStudentDeal: true,
      },
      {
        id: 'vivo-6',
        name: 'Cheesy Garlic Bread',
        nameAr: 'خبز الثوم بالجبنة الذائبة',
        description: 'Crispy oven-baked baguette with garlic butter, parsley, and melted mozzarella',
        price: 50,
        category: 'Paninis & Starters',
        isVegetarian: true,
      },
      {
        id: 'vivo-7',
        name: 'Nutella Calzone Dessert',
        nameAr: 'كالزوني نوتيلا محشي شوكولاتة',
        description: 'Warm folded pizza dough stuffed with melted Nutella and dusted with powdered sugar',
        price: 65,
        category: 'Desserts & Beverages',
        isVegetarian: true,
      },
    ],
  },
  'fue-juice-me-up': {
    restaurantId: 'fue-juice-me-up',
    restaurantName: 'Juice Me Up',
    currency: 'EGP',
    lastUpdated: '2026-09-14',
    note: 'Located at FUE Student Plaza & Courtyard. 100% natural cold-pressed juices, energizing smoothies, and healthy bowls.',
    categories: ['Fresh Juices', 'Signature Smoothies', 'Healthy Bowls & Shots', 'Iced Refreshers'],
    items: [
      {
        id: 'jmu-1',
        name: 'Mango Passion Smoothie',
        nameAr: 'سموذي مانجو باشون فروت',
        description: 'Sweet Egyptian Ismailia mangoes blended with exotic passion fruit and Greek yogurt',
        price: 65,
        category: 'Signature Smoothies',
        isPopular: true,
      },
      {
        id: 'jmu-2',
        name: 'Fresh Orange Booster (Cold Pressed)',
        nameAr: 'عصير برتقال فريش معصور طازج',
        description: 'Pure, fresh 100% cold-pressed Valencia oranges with no added sugar or water',
        price: 45,
        category: 'Fresh Juices',
        isPopular: true,
        isStudentDeal: true,
      },
      {
        id: 'jmu-3',
        name: 'Strawberry Banana Fuel',
        nameAr: 'سموذي فراولة وموز بالحليب',
        description: 'Fresh local strawberries and ripe bananas blended with chilled milk and honey',
        price: 55,
        category: 'Signature Smoothies',
        isStudentDeal: true,
      },
      {
        id: 'jmu-4',
        name: 'Pure Pomegranate Juice',
        nameAr: 'عصير رمان طبيعي ١٠٠٪',
        description: 'Freshly pressed Egyptian red pomegranate seeds rich in natural antioxidants',
        price: 55,
        category: 'Fresh Juices',
        isPopular: true,
      },
      {
        id: 'jmu-5',
        name: 'Watermelon Mint Refresher',
        nameAr: 'عصير بطيخ فريش بالنعناع',
        description: 'Hydrating fresh watermelon blended with garden mint and crushed ice',
        price: 45,
        category: 'Iced Refreshers',
      },
      {
        id: 'jmu-6',
        name: 'Super Acai Berry & Granola Bowl',
        nameAr: 'وعاء أساي بيري مع الجرانولا والفواكه',
        description: 'Blended organic acai berry puree topped with crunchy granola, fresh strawberries, banana slices, and chia seeds',
        price: 95,
        category: 'Healthy Bowls & Shots',
        isPopular: true,
      },
      {
        id: 'jmu-7',
        name: 'Ginger Lemon Honey Immunity Shot',
        nameAr: 'شوت الزنجبيل والليمون والعسل للمناعة',
        description: 'Concentrated fresh ginger root, squeezed lemon, raw honey, and cayenne kick',
        price: 35,
        category: 'Healthy Bowls & Shots',
      },
    ],
  },
  'fue-bouza-roll': {
    restaurantId: 'fue-bouza-roll',
    restaurantName: 'Bouza Roll',
    currency: 'EGP',
    lastUpdated: '2026-09-14',
    note: 'Located at FUE Campus Food Court Kiosk. Hand-rolled ice cream on frozen plates, warm bubble waffles, and dessert shakes.',
    categories: ['Rolled Ice Cream', 'Bubble Waffles & Crepes', 'Shakes & Boba', 'Dessert Bowls'],
    items: [
      {
        id: 'br-1',
        name: 'Lotus Biscoff Ice Cream Roll',
        nameAr: 'آيس كريم رول لوتس بسكوف',
        description: 'Creamy milk base chopped with real Lotus cookies, rolled on sub-zero plate and topped with Lotus sauce and cookie crumble',
        price: 75,
        category: 'Rolled Ice Cream',
        isPopular: true,
      },
      {
        id: 'br-2',
        name: 'Nutella & Fresh Strawberry Roll',
        nameAr: 'آيس كريم رول نوتيلا وفراولة فريش',
        description: 'Sweet dairy cream chopped with ripe strawberries, rolled and drizzled with warm Nutella',
        price: 75,
        category: 'Rolled Ice Cream',
        isPopular: true,
      },
      {
        id: 'br-3',
        name: 'Oreo Cookies & Cream Roll',
        nameAr: 'آيس كريم رول أوريو كوكيز آند كريم',
        description: 'Crushed Oreo cookies rolled with sweet cream base, chocolate drizzle, and an Oreo biscuit',
        price: 65,
        category: 'Rolled Ice Cream',
        isStudentDeal: true,
        isPopular: true,
      },
      {
        id: 'br-4',
        name: 'Kinder Bueno Explosion Roll',
        nameAr: 'آيس كريم رول كيندر بوينو',
        description: 'Crispy hazelnut Kinder Bueno bar chopped, rolled and topped with white chocolate hazelnut sauce',
        price: 85,
        category: 'Rolled Ice Cream',
      },
      {
        id: 'br-5',
        name: 'Crispy Warm Bubble Waffle with Nutella',
        nameAr: 'بابل وافل مقرمش بالنوتيلا والفواكه',
        description: 'Freshly baked warm egg bubble waffle stuffed with vanilla gelato, Nutella, and fresh fruit slices',
        price: 85,
        category: 'Bubble Waffles & Crepes',
        isPopular: true,
      },
      {
        id: 'br-6',
        name: 'Brown Sugar Milk Boba Shake',
        nameAr: 'شيك الحليب بالبوبا وسكر البني',
        description: 'Creamy iced vanilla milk shake with warm chewy brown sugar tapioca pearls',
        price: 70,
        category: 'Shakes & Boba',
      },
    ],
  },
  'fue-saladero': {
    restaurantId: 'fue-saladero',
    restaurantName: 'Saladero',
    currency: 'EGP',
    lastUpdated: '2026-09-14',
    note: 'Located at FUE Campus Food Court & Healthy Bar. Freshly tossed salads, wholesome protein grain bowls, and healthy wraps.',
    categories: ['Signature Bowls', 'Healthy Wraps', 'Warm Grain Bowls', 'Detox Drinks'],
    items: [
      {
        id: 'sal-1',
        name: 'Grilled Chicken Caesar Bowl',
        nameAr: 'سلطة سيزر بالدجاج المشوي',
        description: 'Crisp romaine lettuce, herb-grilled chicken breast, shaved parmesan, garlic herb croutons, and light Caesar dressing',
        price: 110,
        category: 'Signature Bowls',
        isPopular: true,
      },
      {
        id: 'sal-2',
        name: 'Mexican Fiesta Quinoa Bowl',
        nameAr: 'وعاء مكسيكان كينوا وفييستا',
        description: 'Warm fluffy quinoa, grilled spiced chicken, black beans, sweet corn, cherry tomatoes, avocado, and lime cilantro dressing',
        price: 120,
        category: 'Warm Grain Bowls',
        isPopular: true,
        isStudentDeal: true,
      },
      {
        id: 'sal-3',
        name: 'Mediterranean Greek Salad',
        nameAr: 'سلطة يونانية كلاسيكية بالفيتا والزيتون',
        description: 'Crisp cucumbers, vine tomatoes, Kalamata olives, red onion, bell peppers, authentic Greek feta cheese, and oregano vinaigrette',
        price: 90,
        category: 'Signature Bowls',
        isVegetarian: true,
      },
      {
        id: 'sal-4',
        name: 'Avocado, Halloumi & Pesto Wrap',
        nameAr: 'راب أفوكادو وحلوم مشوي بالبيستو',
        description: 'Warm whole wheat tortilla filled with grilled halloumi, fresh avocado slices, mixed greens, and basil pesto',
        price: 95,
        category: 'Healthy Wraps',
        isPopular: true,
        isStudentDeal: true,
        isVegetarian: true,
      },
      {
        id: 'sal-5',
        name: 'Smoked Salmon & Edamame Protein Bowl',
        nameAr: 'وعاء بروتين السلمون المدخن والإدامامي',
        description: 'Norwegian smoked salmon, edamame beans, brown rice, cucumber ribbons, pickled ginger, and sesame ginger dressing',
        price: 155,
        category: 'Warm Grain Bowls',
      },
      {
        id: 'sal-6',
        name: 'Green Detox Cleanser Juice',
        nameAr: 'عصير الديتوكس الأخضر المنعش',
        description: 'Cold-pressed green apples, cucumber, celery, fresh spinach, lemon, and a touch of ginger',
        price: 55,
        category: 'Detox Drinks',
        isVegetarian: true,
      },
    ],
  },
  'p90-costa': {
    restaurantId: 'p90-costa',
    restaurantName: 'Costa Coffee - Point 90 Mall',
    currency: 'EGP',
    lastUpdated: '2026-09-14',
    note: 'Point 90 Mall Branch (Directly across from AUC & near FUE). Complete handcrafted Costa Coffee menu.',
    categories: [
      'Hot Beverages',
      'Iced Beverages',
      'Specialty Drinks',
      'Sandwiches & Toasties',
      'Bakery & Pastries',
      'Desserts & Sweet Treats',
    ],
    items: [
      {
        id: 'p90-cst-1',
        name: 'Signature Flat White',
        nameAr: 'فلات وايت كوستـا كلاسيك',
        description: 'Rich Cortissimo espresso blend with velvety, textured whole milk micro-foam',
        price: 90,
        category: 'Hot Beverages',
        isPopular: true,
      },
      {
        id: 'p90-cst-2',
        name: 'Iced Spanish Latte',
        nameAr: 'سبانيش لاتيه مثلج',
        description: 'Double espresso pulled over chilled sweetened condensed milk and fresh cold milk',
        price: 95,
        category: 'Iced Beverages',
        isPopular: true,
      },
      {
        id: 'p90-cst-3',
        name: 'Salted Caramel Crunch Frostino',
        nameAr: 'فروسـتينو كراميل مملح وكرانش',
        description: 'Blended creamy ice beverage topped with whipped cream, rich caramel drizzle, and crunchy crunchies',
        price: 105,
        category: 'Specialty Drinks',
        isPopular: true,
      },
      {
        id: 'p90-cst-4',
        name: 'Roast Beef & Cheddar Melt Toastie',
        nameAr: 'توست روست بيف وشيدر ساخن',
        description: 'Slices of roast beef, melted mature cheddar, and tangy whole grain mustard on toasted sourdough',
        price: 115,
        category: 'Sandwiches & Toasties',
      },
      {
        id: 'p90-cst-5',
        name: 'Three Cheese & Tomato Focaccia',
        nameAr: 'فوكاشيا ثلاث أجبان وطماطم',
        description: 'Melted mozzarella, cheddar, and gouda with sun-ripened tomatoes on fresh rosemary focaccia',
        price: 90,
        category: 'Sandwiches & Toasties',
        isVegetarian: true,
      },
      {
        id: 'p90-cst-6',
        name: 'Warm Rich Chocolate Fudge Muffin',
        nameAr: 'مافن شوكولاتة فدج دافئ',
        description: 'Decadent chocolate muffin filled with molten fudge cream and Belgian chocolate chips',
        price: 65,
        category: 'Bakery & Pastries',
        isPopular: true,
        isVegetarian: true,
      },
      {
        id: 'p90-cst-7',
        name: 'Carrot & Walnut Cake Slice',
        nameAr: 'كيكة الجزر والجوز بالكريمة',
        description: 'Spiced carrot sponge with roasted walnuts and classic cream cheese frosting',
        price: 75,
        category: 'Desserts & Sweet Treats',
        isVegetarian: true,
      },
    ],
  },
};

/**
 * Helper to fetch or get a menu for a specific restaurant.
 * 1. Returns exact customized default if configured.
 * 2. If available, matches against verified Talabat Egypt real restaurant menus.
 * 3. Falls back to a structured starter template ready for student edits.
 */
export function getMenuForRestaurant(restaurantId: string, restaurantName: string): RestaurantMenu {
  if (DEFAULT_MENUS[restaurantId]) {
    return DEFAULT_MENUS[restaurantId];
  }

  // Look for a verified real Talabat Egypt menu for this brand
  const query = restaurantName.toLowerCase().trim();
  const alias = BRAND_ALIASES[restaurantId] || BRAND_ALIASES[query];
  const typedCached = talabatCachedData as unknown as Record<string, CachedTalabatRestaurant>;

  const cached =
    (alias ? typedCached[alias] : null) ||
    Object.values(typedCached).find(
      (c) =>
        query.includes(c.restaurantName.toLowerCase()) ||
        (c.brand && query.includes(c.brand.toLowerCase())) ||
        restaurantId.toLowerCase().includes(c.restaurantId.toLowerCase())
    );

  if (cached && Array.isArray(cached.items) && cached.items.length > 0) {
    return {
      restaurantId,
      restaurantName,
      currency: cached.currency || 'EGP',
      lastUpdated: cached.lastUpdated,
      note: `Verified real menu extracted from Talabat.com Egypt (${cached.items.length} items)`,
      categories: [...cached.categories],
      items: cached.items.map((it) => ({
        ...it,
        id: `${restaurantId}-${it.id}`,
      })),
    };
  }

  // Fallback generic starter menu ready to be customized by user
  return {
    restaurantId,
    restaurantName,
    currency: 'EGP',
    lastUpdated: new Date().toISOString().split('T')[0],
    note: 'Menu ready for student updates.',
    categories: ['Main Dishes', 'Sandwiches', 'Beverages & Coffee', 'Desserts'],
    items: [
      {
        id: `${restaurantId}-sample-1`,
        name: 'Chef Signature Dish',
        nameAr: 'طبق الشيف المميز',
        description: 'Popular campus meal made fresh to order',
        price: 110,
        category: 'Main Dishes',
        isPopular: true,
      },
      {
        id: `${restaurantId}-sample-2`,
        name: 'Student Lunch Special',
        nameAr: 'وجبة الطلاب الخاصة',
        description: 'Filling meal combo served with sides',
        price: 85,
        category: 'Sandwiches',
        isStudentDeal: true,
      },
      {
        id: `${restaurantId}-sample-3`,
        name: 'Fresh Iced Drink',
        nameAr: 'مشروب منعش مثلج',
        description: 'Chilled specialty beverage',
        price: 50,
        category: 'Beverages & Coffee',
      },
    ],
  };
}
